### ISSUE TITLE
scMappR_and_pathway_analysis error

### ISSUE THREAD

**Issue by ducommunCH** [cran/scMappR#2]
Hello, I am currently trying to run scMappR_and_pathway_analysis using my own DEG list and count matrix. I am using the signature matrix from do_valle_duraes_2020_rnaseq.rda (but also tried others).

I am getting the following error at runtime:

Adjusting Coefficients:
  |                                                  | 0 % ~calculating  Error in if ((up == T)[1]) { : missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Any idea where that might come from? Happy to provide more info.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

**Comment by DustinSokolowski** [comment]
Hey!

I have never seen that error before. Please re-post the issue onto https://github.com/wilsonlabgroup/scMappR/issues. If you could also provide screenshots of your normalized counts, DEGs, and the line(s) of code you're using on that post or send the data files I could help answer much more thoroughly.

Thanks so much!
Dustin

**Comment by ducommunCH** [comment]
Hey!
I think I sorted it out, must have been because of the input data not being in the exact right format (I made everything match the PBMC dataset in the end) as you were probably suspecting.
Anyways thanks for the answer and the great tool!
Will hop over to the wilsonlabgroup github if I have more questions.

Cheers!
Serge
